### ISSUE TITLE
Keine Sechser im Deck

### ISSUE THREAD

**Issue by fekoch** [fkoch-tgm/Mulatschak#1]
Bei Mulatschak haben wir doch kein Sechser? (Bis auf Weli)
Wird aber ins Deck hinzugefügt?
![image](https://user-images.githubusercontent.com/45557700/99305841-9fe6d080-2854-11eb-9945-16ee1abdd9d9.png)

**Comment by ankreppenhofer** [comment]
Die Sechser wurden entfernt.
