### ISSUE TITLE
Wie erkenne ich welche Karte welchen Com gehört?

### ISSUE THREAD

**Issue by ankreppenhofer** [fkoch-tgm/Mulatschak#10]

**Comment by ankreppenhofer** [comment]
Ich meine damit, dass ich mit der getStack Methode zwar das Array bekomm, aber wie weiß ich in welcher Reihenfolge die Karten im Stack liegen.

**Comment by dhegyi-tgm** [comment]
die get stack methode ist jetzt unötig da die player selbst die Karte speichern (muss ich noch hochladen)
