### ISSUE TITLE
Funktionalität für "nächster Spieler" und "welcher Spieler ist dran?"

### ISSUE THREAD

**Issue by fekoch** [fkoch-tgm/Mulatschak#3]
Das Model soll darüber bescheid wissen, welcher Spieler an der Reihe ist.

`nextPlayer()` - der letzte Spieler hat seinen Zug beendet und der nächste ist an der Reihe

`getCurrentPlayer()` - gibt den Spieler der gerade dran ist zurück

**Comment by fekoch** [comment]
Auch mal sowas für die Vorbereitungsphase (Ansagen von Stichen)

**Comment by ankreppenhofer** [comment]
Es wurde behoben (UND DAS BACKEND KANN KEINE ISSUES SCHLIEßEN)
