### ISSUE TITLE
WAS PASSIERT WENN DER SPIELER NICHT ALS ERSTES SPIELT???

### ISSUE THREAD

**Issue by ankreppenhofer** [fkoch-tgm/Mulatschak#6]
Also wenn der Spieler nicht der erste Spieler ist, dann müsste er ja die bereits gespielten Karten sehen? WOHER BEKOMME ICH DIE AUS DEN METHODEN?????????????????????????????

**Comment by dhegyi-tgm** [comment]
my foult
